
name: ðŸ› Bug Report
# title: " "
description: Problems with AnomaVision
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a AnomaVision ðŸ› Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/DeepKnowledge1/AnomaVision/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the AnomaVision [issues](https://github.com/DeepKnowledge1/AnomaVision/issues) and found no similar bug report.
          required: true

  - type: dropdown
    attributes:
      label: AnomaVision Component
      description: |
        Please select the part of AnomaVision where you found the bug.
      multiple: true
      options:
        - "Training"
        - "Validation"
        - "Detection"
        - "Export"
        - "Integrations"
        - "Other"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug
      description: Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        ðŸ’¡ ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please specify the software and hardware you used to produce the bug.
      placeholder: |
        - AnomaVision: AnomaVision ðŸš€ 
        - OS: Ubuntu 20.04
        - Python: 3.9.0
    validations:
      required: false

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem.
      placeholder: |
        ```
        # Code to reproduce your issue here
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/DeepKnowledge1/AnomaVision/pulls) (PR) to help improve AnomaVision for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the AnomaVision [Contributing Guide](code_review_checklist.md) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
