"""HailoRT runtime for complete AnomaVision anomaly HEFs.

The HEF is expected to expose two outputs generated by ``hailo_export``:
``image_scores`` and ``score_map``. Feature extraction and distance calculation
must already be compiled into the HEF. This runtime intentionally contains no
fallback CNN or CPU distance implementation, which prevents accidental partial
quantization on Kria.

The public backend contract matches the other AnomaVision inference backends:
the caller supplies a single normalized RGB image as ``NCHW`` float32 in
``[0, 1]``. The Hailo adapter only changes the layout to ``NHWC`` for the
Hailo VStream; it does not resize or normalize an already-preprocessed tensor.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Tuple

import numpy as np
from PIL import Image

from .base import InferenceBackend


class HailoAnomalyRuntime:
    """Run a complete PaDiM or PatchCore HEF through HailoRT."""

    def __init__(
        self,
        hef_path: str | Path,
        input_size: Tuple[int, int] = (224, 224),
        input_dtype: np.dtype = np.float32,
    ) -> None:
        """Load and configure a complete Hailo-8 HEF."""
        try:
            from hailo_platform import (
                HEF,
                ConfigureParams,
                FormatType,
                HailoStreamInterface,
                InferVStreams,
                InputVStreamParams,
                OutputVStreamParams,
                VDevice,
            )
        except ImportError as exc:  # pragma: no cover - depends on Kria image
            raise RuntimeError(
                "HailoRT is not installed. Install the HailoRT Python package on "
                "the Kria K26 image before loading a HEF."
            ) from exc

        self._api = {
            "ConfigureParams": ConfigureParams,
            "FormatType": FormatType,
            "HEF": HEF,
            "HailoStreamInterface": HailoStreamInterface,
            "InputVStreamParams": InputVStreamParams,
            "InferVStreams": InferVStreams,
            "OutputVStreamParams": OutputVStreamParams,
            "VDevice": VDevice,
        }
        self.hef_path = Path(hef_path)
        if not self.hef_path.exists():
            raise FileNotFoundError(self.hef_path)
        self.input_size = tuple(int(v) for v in input_size)
        self.input_dtype = input_dtype
        self.device = VDevice()
        self.hef = HEF(str(self.hef_path))
        self.network_groups = self.device.configure(self.hef)
        if not self.network_groups:
            raise RuntimeError(f"No network group found in {self.hef_path}")
        self.network_group = self.network_groups[0]
        self.network_group_params = self.network_group.create_params()
        input_infos = self.hef.get_input_vstream_infos()
        if not input_infos:
            raise ValueError(f"The HEF has no input stream: {self.hef_path}")
        self.input_name = input_infos[0].name
        output_names = [info.name for info in self.hef.get_output_vstream_infos()]
        required = {"image_scores", "score_map"}
        missing = sorted(required.difference(output_names))
        if missing:
            raise ValueError(
                "The HEF is not a complete AnomaVision anomaly graph; missing "
                f"outputs: {', '.join(missing)}"
            )
        self.output_names = output_names

    def _prepare_input(self, batch) -> np.ndarray:
        """Adapt the common AnomaVision NCHW contract to Hailo NHWC.

        ``detect.py`` and the other inference backends receive data after the
        dataset resize/normalization stage. Consequently, Hailo must not resize
        or divide by 255 again. This avoids the previous double-preprocessing
        bug where normalized float tensors were cast to uint8 and normalized a
        second time.

        For direct backend use, an HxWx3 uint8/PIL image is also accepted and is
        resized/normalized exactly once.
        """
        if isinstance(batch, Image.Image):
            array = np.asarray(batch.convert("RGB"), dtype=np.uint8)
            array = np.asarray(
                Image.fromarray(array, mode="RGB").resize(
                    (self.input_size[1], self.input_size[0]), Image.Resampling.BILINEAR
                ),
                dtype=np.float32,
            ) / 255.0
            return np.ascontiguousarray(array, dtype=self.input_dtype)

        array = np.asarray(batch)
        if array.ndim == 4:
            if array.shape[0] != 1:
                raise ValueError("HailoBackend currently supports batch size 1")
            array = array[0]

        if array.ndim != 3:
            raise ValueError("batch must be an HxWx3, 3xHxW, or single-image batch")

        # Common AnomaVision contract: CxHxW float32 in [0, 1].
        if array.shape[0] == 3:
            if array.shape[1:] != self.input_size:
                raise ValueError(
                    f"Hailo input must be {self.input_size}, got {array.shape[1:]}"
                )
            array = np.transpose(array, (1, 2, 0))
        # Direct raw-image convenience path: HxWx3 uint8.
        elif array.shape[2] == 3:
            if array.shape[:2] != self.input_size:
                if np.issubdtype(array.dtype, np.integer):
                    array = np.asarray(
                        Image.fromarray(array.astype(np.uint8), mode="RGB").resize(
                            (self.input_size[1], self.input_size[0]),
                            Image.Resampling.BILINEAR,
                        ),
                        dtype=np.float32,
                    )
                else:
                    raise ValueError(
                        f"Hailo input must be {self.input_size}, got {array.shape[:2]}"
                    )
            if np.issubdtype(array.dtype, np.integer):
                array = array.astype(np.float32) / 255.0
        else:
            raise ValueError("batch must be RGB with three channels")

        array = np.asarray(array, dtype=np.float32)
        if array.min() < -1e-6 or array.max() > 1.0 + 1e-6:
            raise ValueError(
                "HailoBackend expects normalized RGB input in [0, 1]. "
                "Use the AnomaVision dataset preprocessing before inference."
            )
        return np.ascontiguousarray(array, dtype=self.input_dtype)

    def predict(self, image) -> Dict[str, np.ndarray]:
        """Run one preprocessed image and return complete anomaly outputs."""
        api = self._api
        input_params = api["InputVStreamParams"].make(
            self.network_group, quantized=False, format_type=api["FormatType"].FLOAT32
        )
        output_params = api["OutputVStreamParams"].make(
            self.network_group, quantized=False, format_type=api["FormatType"].FLOAT32
        )
        tensor = self._prepare_input(image)
        with self.network_group.activate(self.network_group_params):
            with api["InferVStreams"](
                self.network_group, input_params, output_params
            ) as infer_pipeline:
                outputs = infer_pipeline.infer({self.input_name: tensor[None]})
        return {
            "image_scores": np.asarray(outputs["image_scores"]).squeeze(),
            "score_map": np.asarray(outputs["score_map"]).squeeze(),
        }

    def close(self) -> None:
        """Release the Hailo virtual device."""
        release = getattr(self.device, "release", None)
        if callable(release):
            release()

    def __enter__(self) -> "HailoAnomalyRuntime":
        return self

    def __exit__(self, exc_type, exc, traceback) -> None:
        self.close()


class HailoBackend(InferenceBackend):
    """AnomaVision inference backend for a complete Hailo-8 HEF."""

    def __init__(
        self,
        model_path: str | Path,
        device: str = "hailo",
        input_size: Tuple[int, int] = (224, 224),
    ) -> None:
        del device
        self.runtime = HailoAnomalyRuntime(model_path, input_size=input_size)

    def predict(self, batch) -> Tuple[np.ndarray, np.ndarray]:
        """Run a single normalized NCHW image through the HEF."""
        result = self.runtime.predict(batch)
        return result["image_scores"], result["score_map"]

    def warmup(self, batch=None, runs: int = 2) -> None:
        """Warm up the device with a supplied preprocessed image batch."""
        if batch is None:
            raise ValueError("Hailo warmup requires a sample image batch")
        for _ in range(max(1, int(runs))):
            self.predict(batch)

    def close(self) -> None:
        """Release HailoRT resources through the shared backend lifecycle."""
        self.runtime.close()
