"""HailoRT runtime for complete AnomaVision anomaly HEFs.

The HEF is expected to expose two outputs generated by ``hailo_export``:
``image_scores`` and ``score_map``. Feature extraction and distance calculation
must already be compiled into the HEF. This runtime intentionally contains no
fallback CNN or CPU distance implementation, which prevents accidental partial
quantization on Kria.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Tuple

import numpy as np
from PIL import Image

from .base import InferenceBackend


class HailoAnomalyRuntime:
    """Run a complete PaDiM or PatchCore HEF through HailoRT."""

    def __init__(
        self,
        hef_path: str | Path,
        input_size: Tuple[int, int] = (224, 224),
        input_dtype: np.dtype = np.float32,
    ) -> None:
        try:
            from hailo_platform import (
                HEF,
                ConfigureParams,
                FormatType,
                HailoStreamInterface,
                InferVStreams,
                InputVStreamParams,
                OutputVStreamParams,
                VDevice,
            )
        except ImportError as exc:
            raise RuntimeError(
                "HailoRT is not installed. Install the HailoRT Python package on "
                "the target device before loading a HEF."
            ) from exc

        self._api = {
            "ConfigureParams": ConfigureParams,
            "FormatType": FormatType,
            "HEF": HEF,
            "HailoStreamInterface": HailoStreamInterface,
            "InputVStreamParams": InputVStreamParams,
            "InferVStreams": InferVStreams,
            "OutputVStreamParams": OutputVStreamParams,
            "VDevice": VDevice,
        }
        self.hef_path = Path(hef_path)
        if not self.hef_path.exists():
            raise FileNotFoundError(self.hef_path)
        self.input_size = tuple(int(v) for v in input_size)
        self.input_dtype = input_dtype
        self.device = VDevice()
        self.hef = HEF(str(self.hef_path))
        self.network_groups = self.device.configure(self.hef)
        if not self.network_groups:
            raise RuntimeError(f"No network group found in {self.hef_path}")
        self.network_group = self.network_groups[0]
        self.network_group_params = self.network_group.create_params()
        input_infos = self.hef.get_input_vstream_infos()
        output_infos = self.hef.get_output_vstream_infos()
        if not input_infos:
            raise ValueError(f"The HEF has no input streams: {self.hef_path}")
        self.input_name = input_infos[0].name
        self.input_shape = tuple(int(v) for v in input_infos[0].shape)
        output_names = [info.name for info in output_infos]
        required = {"image_scores", "score_map"}
        missing = sorted(required.difference(output_names))
        if missing:
            raise ValueError(
                "The HEF is not a complete AnomaVision anomaly graph; missing "
                f"outputs: {', '.join(missing)}. Re-export/recompile the end-to-end "
                "graph with image_scores and score_map as the two output nodes."
            )
        self.output_names = output_names

    def _preprocess(self, image: Image.Image | np.ndarray | str | Path) -> np.ndarray:
        """Convert an image to the HEF input layout without changing normalization.

        ``detect`` already applies AnomaVision's resize/crop/normalization through
        ``AnodetDataset``. Therefore a float input in this path is considered
        preprocessed and must NOT be divided by 255 again. Raw uint8 images are
        still accepted for direct backend use and are converted to [0, 1].
        """
        if isinstance(image, (str, Path)):
            image = Image.open(image).convert("RGB")
        if isinstance(image, Image.Image):
            image = np.asarray(image)

        array = np.asarray(image)
        if array.ndim == 4:
            if array.shape[0] != 1:
                raise ValueError("HailoAnomalyRuntime currently supports batch size 1")
            array = array[0]

        # Common AnomaVision backend contract is NCHW. Convert to HWC for Hailo.
        if array.ndim == 3 and array.shape[0] == 3 and array.shape[-1] != 3:
            array = np.transpose(array, (1, 2, 0))
        if array.ndim != 3 or array.shape[-1] != 3:
            raise ValueError("image must be an HxWx3 RGB image or 1x3xHxW tensor")

        if array.dtype == np.uint8:
            array = array.astype(np.float32) / 255.0
        else:
            array = array.astype(np.float32, copy=False)

        target_h, target_w = self.input_size
        if array.shape[:2] != (target_h, target_w):
            # This is only for direct raw backend calls. detect normally arrives
            # here already resized/cropped to the model input size.
            if np.nanmin(array) < 0.0 or np.nanmax(array) > 1.0:
                raise ValueError(
                    "Preprocessed float input has values outside [0, 1] and cannot "
                    "be safely resized as a raw image. Use the detect preprocessing pipeline."
                )
            image_u8 = np.clip(array * 255.0, 0, 255).astype(np.uint8)
            array = np.asarray(
                Image.fromarray(image_u8, mode="RGB").resize(
                    (target_w, target_h), Image.Resampling.BILINEAR
                ),
                dtype=np.float32,
            ) / 255.0

        # Hailo parser exports the input as NHWC. Keep the same numeric values
        # used by ONNX/PT and only adapt the memory layout here.
        return array[None].astype(self.input_dtype, copy=False)

    def predict(
        self, image: Image.Image | np.ndarray | str | Path
    ) -> Dict[str, np.ndarray]:
        """Run one image and return complete image and localization outputs."""
        api = self._api
        input_params = api["InputVStreamParams"].make(
            self.network_group, quantized=False, format_type=api["FormatType"].FLOAT32
        )
        output_params = api["OutputVStreamParams"].make(
            self.network_group, quantized=False, format_type=api["FormatType"].FLOAT32
        )
        tensor = self._preprocess(image)
        with self.network_group.activate(self.network_group_params):
            with api["InferVStreams"](
                self.network_group, input_params, output_params
            ) as infer_pipeline:
                outputs = infer_pipeline.infer({self.input_name: tensor})
        return {
            "image_scores": np.asarray(outputs["image_scores"]).squeeze(),
            "score_map": np.asarray(outputs["score_map"]).squeeze(),
        }

    def close(self) -> None:
        release = getattr(self.device, "release", None)
        if callable(release):
            release()

    def __enter__(self) -> "HailoAnomalyRuntime":
        return self

    def __exit__(self, exc_type, exc, traceback) -> None:
        self.close()


class HailoBackend(InferenceBackend):
    """AnomaVision inference backend for a complete Hailo-8 HEF."""

    def __init__(
        self,
        model_path: str | Path,
        device: str = "hailo",
        input_size: Tuple[int, int] = (224, 224),
    ) -> None:
        del device
        self.runtime = HailoAnomalyRuntime(model_path, input_size=input_size)

    def predict(self, batch) -> Tuple[np.ndarray, np.ndarray]:
        """Run one image through the common backend contract."""
        array = np.asarray(batch)
        if array.ndim == 4:
            if array.shape[0] != 1:
                raise ValueError("HailoBackend currently supports batch size 1")
            array = array[0]
        if array.ndim != 3:
            raise ValueError("batch must be an HxWx3 or 1x3xHxW image")
        result = self.runtime.predict(array)
        return result["image_scores"], result["score_map"]

    def warmup(self, batch=None, runs: int = 2) -> None:
        """Warm up the device with a supplied image batch."""
        if batch is None:
            raise ValueError("Hailo warmup requires a sample image batch")
        for _ in range(max(1, int(runs))):
            self.predict(batch)

    def close(self) -> None:
        """Release HailoRT resources through the shared backend lifecycle."""
        self.runtime.close()
