"""HailoRT runtime for complete AnomaVision anomaly HEFs.

The HEF is expected to expose two outputs generated by ``hailo_export``:
``image_scores`` and ``score_map``. Feature extraction and distance calculation
must already be compiled into the HEF. This runtime intentionally contains no
fallback CNN or CPU distance implementation, which prevents accidental partial
quantization on Kria.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Tuple

import numpy as np
from PIL import Image

from .base import InferenceBackend


class HailoAnomalyRuntime:
    """Run a complete PaDiM or PatchCore HEF through HailoRT."""

    def __init__(
        self,
        hef_path: str | Path,
        input_size: Tuple[int, int] = (224, 224),
        input_dtype: np.dtype = np.float32,
    ) -> None:
        """Load and configure a complete Hailo-8 HEF.

        Args:
            hef_path: Path to a HEF exposing ``image_scores`` and ``score_map``.
            input_size: Fixed ``(height, width)`` expected by the HEF.
            input_dtype: Host input dtype passed to HailoRT.

        Raises:
            RuntimeError: If HailoRT is unavailable or has no network group.
            FileNotFoundError: If ``hef_path`` does not exist.
            ValueError: If required anomaly outputs are missing.
        """
        try:
            from hailo_platform import (
                HEF,
                ConfigureParams,
                FormatType,
                HailoStreamInterface,
                InferVStreams,
                InputVStreamParams,
                OutputVStreamParams,
                VDevice,
            )
        except ImportError as exc:  # pragma: no cover - depends on Kria image
            raise RuntimeError(
                "HailoRT is not installed. Install the HailoRT Python package on "
                "the Kria K26 image before loading a HEF."
            ) from exc

        self._api = {
            "ConfigureParams": ConfigureParams,
            "FormatType": FormatType,
            "HEF": HEF,
            "HailoStreamInterface": HailoStreamInterface,
            "InputVStreamParams": InputVStreamParams,
            "InferVStreams": InferVStreams,
            "OutputVStreamParams": OutputVStreamParams,
            "VDevice": VDevice,
        }
        self.hef_path = Path(hef_path)
        if not self.hef_path.exists():
            raise FileNotFoundError(self.hef_path)
        self.input_size = tuple(int(v) for v in input_size)
        self.input_dtype = input_dtype
        self.device = VDevice()
        self.hef = HEF(str(self.hef_path))
        self.network_groups = self.device.configure(self.hef)
        if not self.network_groups:
            raise RuntimeError(f"No network group found in {self.hef_path}")
        self.network_group = self.network_groups[0]
        self.network_group_params = self.network_group.create_params()
        self.input_name = self.hef.get_input_vstream_infos()[0].name
        output_names = [info.name for info in self.hef.get_output_vstream_infos()]
        required = {"image_scores", "score_map"}
        missing = sorted(required.difference(output_names))
        if missing:
            raise ValueError(
                "The HEF is not a complete AnomaVision anomaly graph; missing "
                f"outputs: {', '.join(missing)}"
            )
        self.output_names = output_names

    def _preprocess(self, image: Image.Image | np.ndarray | str | Path) -> np.ndarray:
        """Convert an image path, PIL image, or RGB array to NCHW input."""
        if isinstance(image, (str, Path)):
            image = Image.open(image)
        if isinstance(image, Image.Image):
            image = np.asarray(image.convert("RGB"))
        image = np.asarray(image)
        if image.ndim != 3 or image.shape[2] != 3:
            raise ValueError("image must be an HxWx3 RGB image")
        image = np.asarray(
            Image.fromarray(image.astype(np.uint8), mode="RGB").resize(
                (self.input_size[1], self.input_size[0]), Image.Resampling.BILINEAR
            ),
            dtype=np.float32,
        )
        # Match AnomaVision's tensor contract: NCHW float RGB in [0, 1].
        return np.transpose(image / 255.0, (2, 0, 1))[None].astype(self.input_dtype)

    def predict(
        self, image: Image.Image | np.ndarray | str | Path
    ) -> Dict[str, np.ndarray]:
        """Run one image and return complete image and localization outputs.

        Args:
            image: An image path, PIL RGB image, or HxWx3 RGB array.

        Returns:
            A mapping containing ``image_scores`` and ``score_map`` arrays.
        """
        api = self._api
        input_params = api["InputVStreamParams"].make(
            self.network_group, quantized=False, format_type=api["FormatType"].FLOAT32
        )
        output_params = api["OutputVStreamParams"].make(
            self.network_group, quantized=False, format_type=api["FormatType"].FLOAT32
        )
        tensor = self._preprocess(image)
        with self.network_group.activate(self.network_group_params):
            with api["InferVStreams"](
                self.network_group, input_params, output_params
            ) as infer_pipeline:
                outputs = infer_pipeline.infer({self.input_name: tensor})
        return {
            "image_scores": np.asarray(outputs["image_scores"]).squeeze(),
            "score_map": np.asarray(outputs["score_map"]).squeeze(),
        }

    def close(self) -> None:
        """Release the Hailo virtual device."""
        release = getattr(self.device, "release", None)
        if callable(release):
            release()

    def __enter__(self) -> "HailoAnomalyRuntime":
        return self

    def __exit__(self, exc_type, exc, traceback) -> None:
        self.close()


class HailoBackend(InferenceBackend):
    """AnomaVision inference backend for a complete Hailo-8 HEF."""

    def __init__(
        self,
        model_path: str | Path,
        device: str = "hailo",
        input_size: Tuple[int, int] = (224, 224),
    ) -> None:
        del device
        self.runtime = HailoAnomalyRuntime(model_path, input_size=input_size)

    def predict(self, batch) -> Tuple[np.ndarray, np.ndarray]:
        """Run one image through the common backend contract.

        Args:
            batch: An HxWx3 RGB image or a single-image 1x3xHxW/1xHxWx3 batch.

        Returns:
            A tuple ``(image_scores, score_maps)`` as NumPy arrays.
        """
        array = np.asarray(batch)
        if array.ndim == 4:
            if array.shape[0] != 1:
                raise ValueError("HailoBackend currently supports batch size 1")
            array = (
                np.transpose(array[0], (1, 2, 0)) if array.shape[1] == 3 else array[0]
            )
        elif array.ndim != 3:
            raise ValueError("batch must be an HxWx3 or 1x3xHxW image")
        result = self.runtime.predict(array)
        return result["image_scores"], result["score_map"]

    def warmup(self, batch=None, runs: int = 2) -> None:
        """Warm up the device with a supplied image batch."""
        if batch is None:
            raise ValueError("Hailo warmup requires a sample image batch")
        for _ in range(max(1, int(runs))):
            self.predict(batch)

    def close(self) -> None:
        """Release HailoRT resources through the shared backend lifecycle."""
        self.runtime.close()
