"""Fixed-shape PatchCore graph for Hailo end-to-end deployment."""

from __future__ import annotations

from typing import List, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F

from anomavision.algorithm.common.feature_extraction import ResnetEmbeddingsExtractor


class PatchCoreHailoGraph(nn.Module):
    """Export-friendly PatchCore graph with the complete scoring pipeline.

    The graph keeps the patch scores in their native 14x14 spatial layout.
    Hailo DFC does not support the global ``ReduceMax`` generated by
    ``tensor.amax(dim=(1, 2, 3))``, so the image score is produced with a
    14x14 max-pooling operation instead. This is mathematically equivalent
    for the fixed PatchCore score map and avoids the unsupported reduction.
    """

    def __init__(
        self,
        backbone: str,
        layer_indices: List[int],
        memory_bank: torch.Tensor,
        patch_grid: int = 14,
        input_size: Tuple[int, int] = (224, 224),
    ) -> None:
        super().__init__()
        if patch_grid < 1:
            raise ValueError("patch_grid must be positive")
        if tuple(input_size) != (224, 224) or patch_grid != 14:
            raise ValueError(
                "Hailo PatchCore export currently requires "
                "input_size=(224, 224) and patch_grid=14"
            )

        self.input_size = (224, 224)
        self.patch_grid = 14
        self.layer_indices = list(layer_indices)
        self.extractor = ResnetEmbeddingsExtractor(backbone, torch.device("cpu"))

        # Each normalized memory-bank vector becomes a 1x1 convolution filter.
        # This computes feature-to-memory-bank cosine similarity while preserving
        # the native 14x14 spatial layout and avoiding a patch-score reshape.
        self.register_buffer("memory_bank", F.normalize(memory_bank.float(), dim=-1))

    def forward(self, image: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        embeddings, _, _ = self.extractor(image, layer_indices=self.layer_indices)

        # Fixed ResNet feature layout for the K26 PatchCore artifact.
        # Keep this spatial instead of flattening to 196 patches.
        features = embeddings.reshape(1, 56, 56, 64).permute(0, 3, 1, 2)
        features = F.avg_pool2d(features, kernel_size=4, stride=4)
        features = F.normalize(features, dim=1)

        # [1, 64, 14, 14] x [memory_bank, 64, 1, 1]
        # -> [1, memory_bank_size, 14, 14].
        similarity = F.conv2d(
            features,
            self.memory_bank.unsqueeze(-1).unsqueeze(-1),
        )

        # Best memory-bank match for every spatial patch.
        # Keep the feature/channel dimension so this becomes a Hailo-supported
        # ReduceMax over the features axis.
        best_similarity = similarity.amax(dim=1, keepdim=True)
        distances = torch.sqrt(torch.clamp(2.0 - 2.0 * best_similarity, min=0.0))

        # Native spatial score map: [1, 1, 14, 14] -> [1, 224, 224].
        score_map = F.interpolate(
            distances,
            size=(224, 224),
            mode="bilinear",
            align_corners=False,
        ).squeeze(1)

        # PatchCore image score is the maximum patch distance. Using a fixed
        # 14x14 MaxPool is exactly equivalent to amax(dim=(1,2,3)) here, but
        # exports as MaxPool instead of an unsupported global ReduceMax.
        image_scores = F.max_pool2d(
            distances,
            kernel_size=(14, 14),
            stride=(14, 14),
        )

        # Keep singleton spatial dimensions. Hailo can expose this as a
        # normal 1x1 output without requiring an additional Squeeze/Reshape.
        return image_scores, score_map
