"""HailoRT runtime for complete AnomaVision anomaly HEFs.

The HEF is expected to expose two outputs generated by ``hailo_export``:
``image_scores`` and ``score_map``. Feature extraction and distance calculation
must already be compiled into the HEF. This runtime intentionally contains no
fallback CNN or CPU distance implementation, which prevents accidental partial
quantization on Kria.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Tuple

import numpy as np
from PIL import Image


class HailoAnomalyRuntime:
    """Run a complete PaDiM or PatchCore HEF through HailoRT."""

    def __init__(
        self,
        hef_path: str | Path,
        input_size: Tuple[int, int] = (224, 224),
        input_dtype: np.dtype = np.float32,
    ) -> None:
        try:
            from hailo_platform import (
                HEF,
                ConfigureParams,
                FormatType,
                HailoStreamInterface,
                InferVStreams,
                InputVStreamParams,
                OutputVStreamParams,
                VDevice,
            )
        except ImportError as exc:  # pragma: no cover - depends on Kria image
            raise RuntimeError(
                "HailoRT is not installed. Install the HailoRT Python package on "
                "the Kria K26 image before loading a HEF."
            ) from exc

        self._api = {
            "ConfigureParams": ConfigureParams,
            "FormatType": FormatType,
            "HEF": HEF,
            "HailoStreamInterface": HailoStreamInterface,
            "InputVStreamParams": InputVStreamParams,
            "InferVStreams": InferVStreams,
            "OutputVStreamParams": OutputVStreamParams,
            "VDevice": VDevice,
        }
        self.hef_path = Path(hef_path)
        if not self.hef_path.exists():
            raise FileNotFoundError(self.hef_path)
        self.input_size = tuple(int(v) for v in input_size)
        self.input_dtype = input_dtype
        self.device = VDevice()
        self.hef = HEF(str(self.hef_path))
        self.network_groups = self.device.configure(self.hef)
        if not self.network_groups:
            raise RuntimeError(f"No network group found in {self.hef_path}")
        self.network_group = self.network_groups[0]
        self.network_group_params = self.network_group.create_params()
        self.input_name = self.hef.get_input_vstream_infos()[0].name
        output_names = [info.name for info in self.hef.get_output_vstream_infos()]
        required = {"image_scores", "score_map"}
        missing = sorted(required.difference(output_names))
        if missing:
            raise ValueError(
                "The HEF is not a complete AnomaVision anomaly graph; missing "
                f"outputs: {', '.join(missing)}"
            )
        self.output_names = output_names

    def _preprocess(self, image: Image.Image | np.ndarray) -> np.ndarray:
        if isinstance(image, Image.Image):
            image = np.asarray(image.convert("RGB"))
        image = np.asarray(image)
        if image.ndim != 3 or image.shape[2] != 3:
            raise ValueError("image must be an HxWx3 RGB image")
        image = np.asarray(
            Image.fromarray(image.astype(np.uint8), mode="RGB").resize(
                (self.input_size[1], self.input_size[0]), Image.Resampling.BILINEAR
            ),
            dtype=np.float32,
        )
        # Match AnomaVision's tensor contract: NCHW float RGB in [0, 1].
        return np.transpose(image / 255.0, (2, 0, 1))[None].astype(self.input_dtype)

    def predict(self, image: Image.Image | np.ndarray) -> Dict[str, np.ndarray]:
        """Run one image and return complete image and localization outputs."""
        api = self._api
        input_params = api["InputVStreamParams"].make(
            self.network_group, quantized=False, format_type=api["FormatType"].FLOAT32
        )
        output_params = api["OutputVStreamParams"].make(
            self.network_group, quantized=False, format_type=api["FormatType"].FLOAT32
        )
        tensor = self._preprocess(image)
        with self.network_group.activate(self.network_group_params):
            with api["InferVStreams"](
                self.network_group, input_params, output_params
            ) as infer_pipeline:
                outputs = infer_pipeline.infer({self.input_name: tensor})
        return {
            "image_scores": np.asarray(outputs["image_scores"]).squeeze(),
            "score_map": np.asarray(outputs["score_map"]).squeeze(),
        }

    def close(self) -> None:
        """Release the Hailo virtual device."""
        release = getattr(self.device, "release", None)
        if callable(release):
            release()

    def __enter__(self) -> "HailoAnomalyRuntime":
        return self

    def __exit__(self, exc_type, exc, traceback) -> None:
        self.close()
